// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

export const metadata: Metadata = {
  title: "BetAnalytics - Análises Matemáticas de Apostas",
  description: "Análises estatísticas baseadas em probabilidade matemática dos últimos 30 jogos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className="font-geist-sans antialiased"
        style={{ fontFamily: '"Geist Sans", ui-sans-serif, system-ui, sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
